//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by uippc.rc
//
#define IDS_APP_TITLE                   1
#define IDC_UI                          2
#define ID_VCARD                        3
#define IDOK2                           3
#define ID_VCARD_NICK                   4
#define IDS_JABBER                      101
#define IDR_MENU                        102
#define IDS_WINDOWS                     102
#define IDS_EXIT                        103
#define IDS_HELP                        104
#define IDD_ABOUTBOX                    105
#define IDS_SEND                        107
#define IDD_STATUS                      107
#define IDS_VERSION                     108
#define IDD_DIRECT_PRESENCE             108
#define IDS_REVDATE                     109
#define IDD_EDIT_CONTACT                109
#define IDM_SEND                        110
#define IDD_CONFERENCE                  111
#define IDM_SMILES                      111
#define IDD_ADD_CONTACT                 112
#define IDD_CONFIG_P1                   113
#define IDD_ACCNT1                      113
#define IDC_COMPLETE                    114
#define IDD_ACCNT2                      114
#define IDC_COMPOSING                   115
#define IDD_OPTIONS1                    115
#define IDD_OPTIONS2                    116
#define IDD_OPTIONS3                    117
#define IDD_ACCNT3                      118
#define IDD_OPTIONS4                    119
#define IDC_TAB_CONF                    119
#define IDI_BOMBUS                      130
#define IDI_MESS                        135
#define IDI_MESS_IC                     135
#define IDD_LOC_CONTACT                 136
#define IDD_STATUSY                     137
#define IDB_BITMAP1                     138
#define IDD_MOODS                       138
#define IDI_ICON1                       139
#define IDD_BLAGO                       139
#define IDD_BLAGO1                      140
#define IDD_HISTOR                      140
#define IDC_STATIC_2                    202
#define IDC_STATIC_3                    203
#define IDC_STATIC_4                    204
#define IDC_STATIC_5                    205
#define IDC_STATIC_6                    206
#define IDC_STATIC_7                    207
#define IDC_STATIC_8                    208
#define IDC_STATIC_9                    209
#define IDC_STATIC_10                   210
#define IDC_E_JID                       1003
#define IDC_E_PASSWORD                  1004
#define IDC_X_SSL                       1005
#define IDC_X_SASL                      1006
#define IDC_X_ZLIB                      1007
#define IDC_X_PLAIN                     1008
#define IDC_E_HOSTIP                    1009
#define IDC_E_RESOURCE                  1010
#define IDC_X_ZLIB2                     1010
#define IDC_E_PORT                      1011
#define IDC_X_SSL_WARNINGS              1012
#define IDC_AREV                        1013
#define IDC_X_NSRV                      1013
#define IDC_AVERSION                    1014
#define IDC_E_PRIORITY                  1015
#define IDC_AVERSION2                   1015
#define IDC_X_PRESAVE                   1016
#define IDC_C_STATUS                    1017
#define IDC_C_PRESET                    1018
#define IDC_E_STATUS                    1019
#define IDC_SPIN_PRIORITY               1021
#define IDC_E_NICK                      1023
#define IDC_C_SERVICE                   1024
#define IDC_C_GROUP                     1025
#define IDC_E_DOL                       1025
#define IDC_X_SUBSCR                    1026
#define IDC_E_LOCMES                    1026
#define IDC_SAVE                        1028
#define IDC_DELETE                      1029
#define IDC_E_ROOM                      1030
#define IDC_E_SERVER                    1031
#define IDC_C_NICK                      1033
#define IDC_E_HISTSZ                    1034
#define IDC_SPIN_HIST_SZ                1035
#define IDC_C_BOOKMARK                  1036
#define IDC_X_AUTOJOIN                  1037
#define IDC_X_GROUPS                    1041
#define IDC_X_OFFLINES                  1042
#define IDC_X_PRESENCESORT              1043
#define IDC_X_DELIVERY                  1044
#define IDC_X_CLIENT                    1044
#define IDC_X_PRESENCESORT2             1044
#define IDC_AUTOJOINROOM                1044
#define IDC_X_COMPOSING                 1045
#define IDC_AVTOSTATUS                  1045
#define IDC_X_SOUNDS                    1046
#define IDC_X_VIBRA                     1047
#define IDC_X_DIALUP                    1048
#define IDC_SIP1                        1049
#define IDC_X_BLINK1                    1049
#define IDC_X_AUTOCONNECT               1050
#define IDC_X_MSG_FONT_HEIGHT           1051
#define IDC_X_SOUNDS3                   1051
#define IDC_X_BLINK2                    1051
#define IDC_X_MSG_FONT_WIDTH            1052
#define IDC_CHECK1                      1052
#define IDC_SOUNDCOM                    1052
#define IDC_EDITX2                      1052
#define IDC_X_ROSTER_FONT_HEIGHT        1053
#define IDC_X_VSMESS                    1053
#define IDC_EDITX3                      1053
#define IDC_TUN_STATUS                  1053
#define IDC_X_ROSTER_FONT_WIDTH         1054
#define IDC_X_VSTRYMESS                 1054
#define IDC_TUN_PEP                     1054
#define IDC_X_MSG_FONT_TOLSH            1055
#define IDC_SOUND_STATUS                1055
#define IDC_X_AWAT                      1056
#define IDC_SOUND_STATUS2               1057
#define IDC_VS_STATUS                   1057
#define IDC_TIME_AVTOSTATUS             1057
#define IDC_VS_CONFCHAT                 1058
#define IDC_AVTOSTATUS_MESS             1058
#define IDC_ID_AVTOSTATUS               1059
#define IDC_LIST1                       1060
#define IDC_X_HIS_MUCD                  1061
#define IDC_E_JID2                      1062
#define IDC_E_SHIR                      1063
#define IDOK3                           1064
#define IDC_MOODS                       1065
#define IDC_MES_MOODS                   1066
#define IDC_EDIT1                       1068
#define IDC_EDIT2                       1069
#define IDC_EDIT3                       1070
#define IDC_EDIT4                       1071
#define IDC_NEWS_EDIT                   1072
#define IDC_AHW                         1095
#define IDC_X_HISTORY                   1098
#define IDC_X_SIP                       1099
#define IDC_X_HIS_CH_D                  1101
#define IDC_X_HISTORY3                  1102
#define IDC_XML_LOG                     1145
#define IDC_SB                          1682
#define IDC_RECONNECT_TRIES             5325
#define IDC_PINGAKIV                    5326
#define IDC_PONGALIV                    5327
#define IDS_WINDOWS23                   12987
#define IDM_JABBER                      32775
#define IDM_JABBER_STREAMINFO           32777
#define IDM_WINDOWS_ROSTER              32782
#define IDM_WINDOWS_LOG                 32783
#define IDM_JABBER_ACCOUNT              32785
#define IDM_JABBER_STATUS               32787
#define ID_JABBER_ADDACONTACT           32788
#define ID_JABBER_TOOLS                 32789
#define ID_TOOLS_SERVICEDISCOVERY       32790
#define ID_JABBER_JOINCONFERENCE        32791
#define ID_TOOLS_FILETRANSFERS          32792
#define ID_JABBER_OPTIONS               32793
#define ID_TOOLS_STREAMINFO             32794
#define ID_TOOLS_MYVCARD                32795
#define ID_Menu                         32796
#define ID_WINDOWS                      32798
#define ID_JABBER_ACCOUNT2              32799
#define IDM_JABBER_ACCOUNT2             32800
#define ID_STATUS_ONLINE                32801
#define ID_STATUS_AWAY                  32802
#define ID_STATUS_FFC                   32803
#define ID_STATUS_OFFLINE               32804
#define IDM_HELP_ABOUT2                 32804
#define ID_CONTACT_SUBSCRIBE            32805
#define ID_Menu32805                    32805
#define ID_SUBSCRIBE_GRAND              32806
#define ID_SUPP                         32806
#define ID_SUBSCRIPTION_GRANTSUBSCRIPTION 32807
#define ID_32807                        32807
#define ID_SUBSCRIPTION_REVOKESUBSCRIPTION 32808
#define ID_BLAGO                        32808
#define ID_CONTACT_INFO                 32809
#define ID_PEP_32809                    32809
#define IDM_STATUS_ONLINE               32810
#define ID_STATUS_EXTENDEDAWAY          32811
#define AKTIV_PEP                       32811
#define ID_STATUS_DND                   32812
#define ID_32812                        32812
#define IDM_STATUS_OFFLINE              32813
#define IDM_STATUS_DND                  32814
#define IDM_STATUS_EXTENDEDAWAY         32815
#define IDM_STATUS_AWAY                 32816
#define IDM_STATUS_FFC                  32817
#define IDM_SHOW_STATUS_IN_MUC          32818
#define IDM_SHOW_STATUS_IN_SIMPLE_CHAT  32819
#define IDM_SAVE_HISTORY_MUC            32820
#define IDC_X_HIS_MUC_D                 32820
#define IDM_SAVE_HISTORY_IN_HTML        32821
#define CGETNICK                        32821
#define CQUOTE                          32822
#define CCLRMSGS                        32823
#define CCLPMSGS                        32824
#define CSAVECHAT                       32825
#define GLOBAL_STATUS                   32826
#define SB_                             36585
#define ID_TOOLS_COLORRE                37801
#define IDM_EXIT                        40000
#define IDM_HELP_ABOUT                  40002
#define AKTIVW                          42350
#define WM_VYBOR                        42351
#define WM_STAV                         42352
#define WM_OTMENA_VYBOR                 42353
#define IDC_WM_VYBOR                    42354
#define IDC_WM_STAV                     42355
#define MOODS_AKTIV                     42358
#define ID_32806                        42360
#define NEWS                            42362
#define CLEARMESS						42365
#define CLEAR2M							42366
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1073
#define _APS_NEXT_SYMED_VALUE           116
#endif
#endif
